In [1]:
import pandas as pd

Loading the population dataset and removing extra columns, leaving only columns: 
- Time - renamed to Year
- Age
- Sex 
- Value - renamed to Population

In [2]:
df = pd.read_csv('..\dataset\population_dataset.csv')

df = df.drop(columns=['IndicatorId', 
                      'IndicatorName', 
                      'IndicatorShortName', 
                      'Source', 
                      'SourceYear', 
                      'Author', 
                      'LocationId', 
                      'Location', 
                      'Iso2', 
                      'Iso3', 
                      'TimeId', 
                      'VariantId', 
                      'Variant', 
                      'SexId', 
                      'AgeId',
                      'AgeStart', 
                      'AgeEnd', 
                      'Category', 
                      'CategoryId', 
                      'EstimateTypeId', 
                      'EstimateType', 
                      'EstimateMethodId', 
                      'EstimateMethod'])

df = df.rename(columns={'Value': 'Population',
                        'Time': 'Year'})

df.head()

   Year     Sex    Age  Population
0  2000    Male      0     81546.0
1  2000  Female      0     77481.0
2  2000    Male   0-14    699618.5
3  2000  Female   0-14    665838.5
4  2000    Male  15-64   2709145.5

Current age groups are: 0, 0-14, 15-64, 65+, 90+.
Desired age groups defined by the task are: 0, 1-14, 15-64, 65-89 and 90+. In the following code, defined age groups are derived from what the UN Population Dataset provided us.

In [3]:
cleaned_rows = []

for year in df['Year'].unique():
    for sex in df['Sex'].unique():

        subset = df[(df['Year'] == year) & (df['Sex'] == sex)]

        pop_0 = subset.loc[subset['Age'] == '0', 'Population'].values[0]
        pop_0_14 = subset.loc[subset['Age'] == '0-14', 'Population'].values[0]
        pop_15_64 = subset.loc[subset['Age'] == '15-64', 'Population'].values[0]
        pop_65_plus = subset.loc[subset['Age'] == '65+', 'Population'].values[0]
        pop_90_plus = subset.loc[subset['Age'] == '90+', 'Population'].values[0]

        pop_1_14 = pop_0_14 - pop_0
        pop_65_89 = pop_65_plus - pop_90_plus

        cleaned_rows.append([year, "0", sex, pop_0])
        cleaned_rows.append([year, "1-14", sex, pop_1_14])
        cleaned_rows.append([year, "15-64", sex, pop_15_64])
        cleaned_rows.append([year, "65-89", sex, pop_65_89])
        cleaned_rows.append([year, "90+", sex, pop_90_plus])

df = pd.DataFrame(cleaned_rows, columns=['Year', 'Age', 'Sex', 'Population'])

df.head(20)

    Year    Age     Sex  Population
0   2000      0    Male     81546.0
1   2000   1-14    Male    618072.5
2   2000  15-64    Male   2709145.5
3   2000  65-89    Male    457217.0
4   2000    90+    Male      9290.0
5   2000      0  Female     77481.0
6   2000   1-14  Female    588357.5
7   2000  15-64  Female   2701078.0
8   2000  65-89  Female    737566.5
9   2000    90+  Female     33174.0
10  2001      0    Male     79831.0
11  2001   1-14    Male    613209.5
12  2001  15-64    Male   2727804.5
13  2001  65-89    Male    463285.0
14  2001    90+    Male      9882.5
15  2001      0  Female     75540.0
16  2001   1-14  Female    583888.5
17  2001  15-64  Female   2718357.5
18  2001  65-89  Female    735558.0
19  2001    90+  Female     34876.0

In [4]:
print(df.columns)
print(df.shape)
print(df["Year"].unique())
print(df["Age"].unique())
print(df["Sex"].unique())

Index(['Year', 'Age', 'Sex', 'Population'], dtype='object')
(200, 4)
[2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019]
['0' '1-14' '15-64' '65-89' '90+']
['Male' 'Female']

Saving the cleaned dataset to a new CSV file.

In [7]:
df.to_csv('..\dataset\cleaned_population_dataset.csv', index=False)